### ISSUE TITLE
Ruby 2.0 Support?

### ISSUE THREAD

**Issue by Kamek** [shawn42/gamebox#93]
Just installed on a fresh install of ruby 2.0 and `gamebox new zapper` crashes horribly.
`ruby -v`
`ruby 2.0.0p451 (2014-02-24) [i386-mingw32]`
`uname -a`
`MINGW32_NT-6.2 SPELLBOOK 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown`

**Comment by shawn42** [comment]
Closing because Gosu now supports Ruby 2.x
