### ISSUE TITLE
Image Rendering Bug

### ISSUE THREAD

**Issue by zotherstupidguy** [shawn42/gamebox#99]
We noticed a rendering bug for images, it draws images from the top left corner instead of the center.

**Comment by zotherstupidguy** [comment]
![gamebox_rendering_bug](https://cloud.githubusercontent.com/assets/10923261/7352155/9f71c930-ed12-11e4-9e98-4549e9c2540f.png)

**Comment by shawn42** [comment]
This was observed in omg_aliens. It was a configuration option that was added to gamebox, but not used properly in omg_aliens. Has now been fixed there.
